# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 09:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dquote', '0002_auto_20180207_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='dqoute',
            name='person_en',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='作者英文名'),
        ),
        migrations.AddField(
            model_name='dqoute',
            name='quote_en',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='英文名言'),
        ),
    ]
