# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dquote', '0003_auto_20180208_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dqoute',
            name='person',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='dqoute',
            name='person_en',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='作者英文名'),
        ),
    ]
