# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import utils.image.handlers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(default='', upload_to=utils.image.handlers.UUIDFilename('ad/images/'))),
                ('link', models.URLField(max_length=255)),
                ('enable', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField(choices=[(0, '顶部主广告'), (1, '页中长广告'), (2, '页中第二长广告'), (3, '侧边顶'), (4, '侧边栏中'), (5, '侧边栏下')], default=0)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'verbose_name': 'advertisement',
                'verbose_name_plural': 'advertisement',
            },
        ),
    ]