# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-09 09:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='end_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='advertisement',
            name='start_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
