# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-04 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20180209_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='user',
            field=models.CharField(default='root', max_length=200),
        ),
    ]
