# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoinFork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=128)),
                ('coin_ename', models.CharField(blank=True, max_length=128, null=True)),
                ('fork_name', models.CharField(max_length=128)),
                ('fork_ename', models.CharField(blank=True, max_length=128, null=True)),
                ('block_mining_time', models.IntegerField(help_text='平均出块时间, mint')),
                ('fork_height', models.IntegerField(help_text='分叉高度')),
                ('current_height_api', models.URLField(default='https://blockchain.info/q/getblockcount', help_text='当前区块高度API')),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
