# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-12 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coinfork', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinfork',
            name='fork_alias',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='coinfork',
            name='official_site',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinfork',
            name='related_article',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coinfork',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='incoming', max_length=100, no_check_for_status=True, verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='block_mining_time',
            field=models.IntegerField(default=10, help_text='平均出块时间, mint'),
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='coin_ename',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='coin_name',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='fork_ename',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='fork_name',
            field=models.CharField(max_length=64),
        ),
    ]
