# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-14 02:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinfork', '0002_auto_20171212_1557'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinfork',
            options={'ordering': ['-status', 'fork_height']},
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='fork_height',
            field=models.FloatField(help_text='分叉高度'),
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='fork_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
