# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinfork', '0003_auto_20171214_1058'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coinfork',
            options={'ordering': ['-status', 'fork_height'], 'verbose_name': '加密货币分叉', 'verbose_name_plural': '加密货币分叉'},
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='block_mining_time',
            field=models.FloatField(default=10, help_text='平均出块时间, mint'),
        ),
        migrations.AlterField(
            model_name='coinfork',
            name='fork_height',
            field=models.IntegerField(help_text='分叉高度'),
        ),
    ]
