# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-15 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinfork', '0004_auto_20171215_1053'),
        ('coinfork', '0004_auto_20171215_1403'),
    ]

    operations = [
    ]
