# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-02 08:17
from __future__ import unicode_literals

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('coinfork', '0006_auto_20180201_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinfork',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='incoming', max_length=100, no_check_for_status=True, verbose_name='状态'),
        ),
    ]
