# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinfork', '0011_coinfork_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinfork',
            name='user',
        ),
    ]
