# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0002_auto_20180530_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='age',
            field=models.CharField(default=0, max_length=5),
        ),
        migrations.AddField(
            model_name='writer',
            name='sex',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='article',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
