# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-31 05:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Model', '0004_auto_20180531_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='article',
        ),
    ]
