# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 03:32
from __future__ import unicode_literals

from django.db import migrations, models
import model_utils.fields
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nav',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('other_name', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('web_site', models.URLField()),
                ('score', models.IntegerField(default=0)),
                ('status', model_utils.fields.StatusField(choices=[('remove', 'remove'), ('draft', 'draft'), ('published', 'published')], default='published', max_length=100, no_check_for_status=True, verbose_name='status')),
                ('category', models.CharField(max_length=64)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['-score'],
            },
        ),
    ]
