# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_auto_20170907_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='highlight',
            field=models.BooleanField(default=False),
        ),
    ]
