# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:10
from __future__ import unicode_literals

import caching.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0007_auto_20170911_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=64)),
                ('ename', models.CharField(max_length=64)),
            ],
            bases=(caching.base.CachingMixin, models.Model),
        ),
    ]
