# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='navs', to='nav.Category'),
        ),
    ]
