# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0009_nav_cate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nav',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='cname',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='category',
            name='ename',
            field=models.CharField(db_index=True, max_length=64),
        ),
    ]
