# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0012_auto_20170925_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='license',
            new_name='software_license',
        ),
    ]
