# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0014_auto_20170926_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
