# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0015_auto_20170926_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='origin_link',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='mainnet_contract_address',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
