# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-26 12:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0016_auto_20170926_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_updated',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
