# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0017_auto_20170926_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='mainnet_contract_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
