# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0019_auto_20170928_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='nav',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='nav',
            name='score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
