# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 05:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0020_auto_20170929_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
