# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0022_nav_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nav',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
