# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0023_auto_20171009_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_cn',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='highlight',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
