# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 06:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0024_auto_20171012_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='state',
            new_name='status',
        ),
    ]
