# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0025_auto_20171012_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='whitepaper',
            field=models.URLField(default='', verbose_name='whitepaper'),
        ),
    ]
