# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0026_project_whitepaper'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='identified_code',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True, unique=True),
        ),
    ]
