# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0028_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='中文描述'),
        ),
    ]
