# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 08:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0030_subnav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnav',
            name='location',
        ),
        migrations.AlterField(
            model_name='subnav',
            name='cname',
            field=models.CharField(max_length=64, unique=True, verbose_name='中文名称'),
        ),
        migrations.AlterField(
            model_name='subnav',
            name='description',
            field=models.TextField(default='', max_length=256, verbose_name='网站描述，一句话'),
        ),
        migrations.AlterField(
            model_name='subnav',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='联系邮件'),
        ),
        migrations.AlterField(
            model_name='subnav',
            name='ename',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='英文名称'),
        ),
        migrations.AlterField(
            model_name='subnav',
            name='web_site',
            field=models.URLField(default='http://sina.com', verbose_name='网站链接'),
            preserve_default=False,
        ),
    ]
