# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 12:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0032_auto_20171026_1136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-order'], 'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='nav',
            options={'ordering': ['-score'], 'verbose_name': '导航站点', 'verbose_name_plural': '导航站点'},
        ),
    ]
