# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 04:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0033_auto_20171104_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnav',
            options={'verbose_name': '用户提交网址', 'verbose_name_plural': '用户提交网址'},
        ),
    ]
