# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-08 07:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0034_auto_20171109_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnav',
            name='description',
            field=models.TextField(blank=True, default='', max_length=256, null=True, verbose_name='网站描述，一句话'),
        ),
    ]
