# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 04:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0035_auto_20171208_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subnav',
            options={'ordering': ['-created'], 'verbose_name': '用户提交网址', 'verbose_name_plural': '用户提交网址'},
        ),
        migrations.AddField(
            model_name='subnav',
            name='created',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
