# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-16 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0036_auto_20180116_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subnav',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
