# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 04:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flink', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flink',
            options={'ordering': ['-score'], 'verbose_name': '友情链接', 'verbose_name_plural': '友情链接'},
        ),
    ]
