# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-05 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flink', '0002_auto_20171109_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='flink',
            name='user',
            field=models.CharField(default='Soooo', max_length=666),
        ),
    ]
